"""Apply committed LLM OCR-fix patches to chunked/passages.jsonl.

Phase 3 (plans/2026-07-07-swi-v2-ocr-cleanup-verification.md): unlike
Phase 1 (raw-file fixes) and Phase 2 (permanent regex rules in
ocr_cleaning.py), Phase 3's fixes are per-passage LLM output and can't be
re-derived from raw/ + committed rules. This script is what makes them
reproducible: it re-applies a committed metadata/llm-ocr-fixes-*.json patch
to chunked/passages.jsonl (gitignored, regenerated by the normal pipeline),
so a from-scratch corpus rebuild doesn't silently lose this pass.

Each patch file: [{"id": passage_id, "source_id": ..., "text": fixed_text}, ...]

Provenance -- 2026-07-07, Haiku 4.5, strict "fix OCR errors only, no
wording/spelling/punctuation changes" prompt, applied as a reviewed diff
after Wilson's go-ahead. 3 of 4 attempted sources succeeded (39 passages,
jw-general-rules/cw-sermon-ii/cw-sermon-iii); jw-genuine-christianity was
blocked by content filtering on 2 of 3 attempts (likely the Anaxagoras/
tyrant torture reference read oddly to a classifier alongside heavy OCR
garbling) and is not included -- left for a future session.

Usage: python3 scripts/apply_llm_ocr_fixes.py
Re-run clean_corpus.py + extract_scripture_references.py + the sentinel
suite afterward, same as any other passages.jsonl-level change.
"""
import glob
import json
from pathlib import Path

BASE = Path(__file__).parent.parent
PASSAGES = BASE / "chunked" / "passages.jsonl"
PATCH_GLOB = str(BASE / "metadata" / "llm-ocr-fixes-*.json")


def main():
    patches = {}
    for path in sorted(glob.glob(PATCH_GLOB)):
        for entry in json.load(open(path, encoding="utf-8")):
            patches[entry["id"]] = entry["text"]
    print(f"Loaded {len(patches)} passage fixes from {len(glob.glob(PATCH_GLOB))} patch file(s)")

    rows = [json.loads(l) for l in open(PASSAGES, encoding="utf-8")]
    changed = 0
    seen = set()
    for r in rows:
        if r["id"] in patches:
            seen.add(r["id"])
            if r["text"] != patches[r["id"]]:
                r["text"] = patches[r["id"]]
                changed += 1

    missing = set(patches) - seen
    if missing:
        print(f"WARNING: {len(missing)} patched ids not found in passages.jsonl: {sorted(missing)[:5]}...")

    with open(PASSAGES, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    print(f"Applied {changed} text changes to {PASSAGES}")


if __name__ == "__main__":
    main()
